version: "3.9"
services:
    postgres:
        image: postgres:14-alpine
        restart: always
        ports:
            - "5432"
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            default:
                ipv4_address: 10.0.10.254
    web:
        build: ./website
        ports:
            - "3001-3010:3000"
        restart: always
        environment:
            - NODE_ENV=${NODE_ENV}
            - DATABASE_URL=${DATABASE_URL}
            - AUTH_SECRET=${AUTH_SECRET}
            - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
            - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - RESEND_API_KEY=${RESEND_API_KEY}
            - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
            - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
        networks:
            - default
        depends_on:
            - postgres
        deploy:
            replicas: 10
            mode: replicated
            endpoint_mode: dnsrr

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 10.0.10.0/24
                  gateway: 10.0.10.1
