version: "3.9"
services:
    postgres:
        image: postgres:14-alpine
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
        env_file:
            - ./db/.env
        networks:
            default:
                ipv4_address: 192.168.0.20
    web:
        build: ./website
        ports:
            - "3000"
        restart: always
        networks:
            - default
        deploy:
            replicas: 2
            mode: replicated
            endpoint_mode: dnsrr

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24
                  gateway: 192.168.0.1
