version: "3.9"
services:
  redis:
    build: ./rate-limiter
    ports:
      - "6000:6379"
    restart: always
    networks:
      - default

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file:
      - ./db/.env
    networks:
      default:
        ipv4_address: 10.0.10.254
  web:
    build: ./website
    ports:
      - "3001-3010:3000"
    restart: always
    networks:
      - default
    depends_on:
      - postgres
      - redis
    deploy:
      replicas: 10
      mode: replicated
      endpoint_mode: dnsrr

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24
          gateway: 10.0.10.1
